In [2]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)

In [8]:
x.reshape(3, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
y = torch.randn(2, 3)

In [19]:
z = torch.tensor([[1,2,3,4], [5,6,7,8]])
z

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [20]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])